name: Build
on:
  push:
    tags: ['*']
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 13
      - uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/') }}
          skip_build: true
          use_vue_cli: true
