name: Build
on:
  push:
    tags: ['*']
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 13
      - run: npm ci
      - run: npm run electron:build -- --publish always
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
